### ISSUE TITLE
Can you add a function to refresh the summary of numbers?

### ISSUE THREAD

**Issue by huyingjie** [tschoffelen/vibe#1]
I like your app. The app can automatically show the summary of numbers. But if I want to refresh the numbers after checking several tasks, I have to close and reopen the app. I hope that there is a button I can press to automatically refresh the numbers. 

Thank you

**Comment by tschoffelen** [comment]
That should be happening automatically every 30 seconds, but I did not test that to be honest (https://github.com/tschoffelen/vibe/blob/master/Vibe/AppDelegate.swift#L27).

**Comment by tschoffelen** [comment]
Tested & confirmed that it does currently refresh automatically. Feel free to re-open this issue if I misunderstood you!
