### ISSUE TITLE
Doesn't work on any OS X lower than 10.11

### ISSUE THREAD

**Issue by anastasiuspernat** [tschoffelen/vibe#2]
Seems to be a great software! I was looking for something like that for a long time!
But it doesn't run on my Mac that has OS X 10.10. Do you have plans to port it to legacy OSs?

**Comment by tschoffelen** [comment]
Hi! Just added a version that should also run on OSX10.10: https://github.com/tschoffelen/vibe/releases/tag/0.1.2

**Comment by tschoffelen** [comment]
Did that work @anastasiuspernat? Want to know if I can close this ticket.

**Comment by anastasiuspernat** [comment]
Wow, yhanks for the fast fix! 
It opens, but the text on the top is cut like on the attached picture.
![](https://www.dropbox.com/s/h9z0z6u8t2h3zqm/VibeScreenshot2.png?dl=0&raw=1)
Also everything is very buggy when windows is being scaled.

**Comment by tschoffelen** [comment]
Ah, I see. Seems like the constraints that it uses don't work correctly. With OS X 10.12 coming up in the the next 2 months, I don't think it's necessary to spend a lot of time on correcting this, right?

**Comment by anastasiuspernat** [comment]
I dunno, it depends on the scope of your project! I'm personally not going to upgrade unless I need to, my environment works perfect on 10.10 and I don't see any reasons for upgrading. Also I have a lot of friends on 10.9 and 10.10.

P.S. Tried it on 10.11 and the bugs with repainting when scaling remained.
Thank you!
