### ISSUE TITLE
Needs a beautiful icon 💅

### ISSUE THREAD

**Issue by eivindml** [tschoffelen/vibe#5]
This doesn't look to good! The app should have a icon. Maybe someone over at dribbble.com can create one. 

<img width="65" alt="screen shot 2017-02-11 at 10 48 38" src="https://cloud.githubusercontent.com/assets/202450/22852914/c74a1a68-f047-11e6-9c2b-c177d06d3493.png">

**Comment by tschoffelen** [comment]
Tried something, not great, but it's better than not having an icon of course. Any suggestions are very welcome.

![Icon](https://cloud.githubusercontent.com/assets/666220/22853717/c710dc24-f05d-11e6-97f5-258bb64faefa.png)

**Comment by eivindml** [comment]
Looks great! :)
