### ISSUE TITLE
Completed In Last 7 Days Shows 10 Days

### ISSUE THREAD

**Issue by andreamocko** [tschoffelen/vibe#8]
The latest release now shows 10 days worth of data under the completed tasks last 7 days section.

**Comment by tschoffelen** [comment]
codemill$2

**Comment by tschoffelen** [comment]
@tschoffelen has been assigned to this task.

**Comment by tschoffelen** [comment]
@tschoffelen has been unassigned from this task.

**Comment by tschoffelen** [comment]
Do you have a screenshot of that? Mine does show only 7 days:

![image](https://cloud.githubusercontent.com/assets/666220/22861958/fba69e34-f124-11e6-874e-e0b124d9a67c.png)

**Comment by andreamocko** [comment]
Here's one. Looks like dates are showing up more than once with different numbers...
<img width="309" alt="2017-02-12 screenshot" src="https://cloud.githubusercontent.com/assets/21124540/22865122/85506ff6-f12b-11e6-8871-8e3c23e5fdef.png">

**Comment by tschoffelen** [comment]
Ah, I know where the problem lies. Thanks, will fix it soon!

**Comment by tschoffelen** [comment]
I think I fixed it in version 0.1.4, could you confirm?

**Comment by andreamocko** [comment]
It's fixed. Thanks for checking it out!
