### ISSUE TITLE
Crashing every Launch

### ISSUE THREAD

**Issue by jbrewlet** [tschoffelen/vibe#9]
For some reason today, after installing my newly purchased OmniFocus 2 license, Vibe won't open and crashes every time. I was using it during my trial. Tried to remove the app and reinstall to no luck.

macOS Sierra: 10.12.3

**Comment by tschoffelen** [comment]
Do you have any kind of crash log, e.g. from the Console? Then I can check out where the problem lies exactly.

**Comment by jbrewlet** [comment]
Sure. 
I'm not sure how the best way to do this:

[Vibe_2017-03-16-101740.crash.zip](https://github.com/tschoffelen/vibe/files/848517/Vibe_2017-03-16-101740.crash.zip)

Hope that helps. Thanks for making the app!

**Comment by jbrewlet** [comment]
I'm not sure what has happened but now Vibe doesn't crash on startup. Hurray?!

**Comment by tschoffelen** [comment]
Ah, nice!
